# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DownloadSecureFile@1
  name: appsettingsProductionJsonFile
  displayName: 'Download appsettings.Production.json'
  inputs:
    secureFile: 'notifyme.appsettings.Production.json'

- script: |
    echo copying $(appsettingsProductionJsonFile.secureFilePath) to notifyme.server...
    sudo cp $(appsettingsProductionJsonFile.secureFilePath) $(Build.ArtifactStagingDirectory)/src/notifyme.server/appsettings.Production.json

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    projects: '**/notifyme.server.csproj'
    command: 'restore'
    includeNuGetOrg: true

- task: DotNetCoreCLI@2
  inputs:
    projects: '**/notifyme.server.csproj'
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/notifyme.server.tests.csproj'
    testRunTitle: 'Run Tests'
  displayName: test