version: '3.4'

services:
  notifymeserver:
    image: notifymeserver
    build:
      context: .
      dockerfile: src/notifyme.server/Dockerfile
    volumes:
      - /var/notifymeapp/Data Stores:/app/Data Stores
