version: '3.4'

services:
  notifymeserver:
    user: appuser
    image: notifymeserver
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: src/notifyme.server/Dockerfile
    volumes:
      - notifymeappdata:/app/Data Stores

volumes:
  notifymeappdata:
